// src/main/searchManager.js

// This file contains the core fuzzy search algorithm, manages the in-memory
// search index, and provides an API for updating and querying the index.
// It is deliberately decoupled from file system operations.

let searchIndex = []; // Stores lightweight index items

// --- START: Memory Optimization ---
// Use numeric IDs for more compact storage.
let _nextProjectId = 1;
let _nextNoteId = 1;

// Centralized metadata maps, keyed by their new unique numeric ID.
const _projectMetadata = new Map(); // Stores project details: projectId -> { name: string, path: string }
const _noteMetadata = new Map();    // Stores note details:   noteId    -> { name: string, projectId: number }

// Maps to look up numeric IDs from their original string identifiers.
const _projectRefMap = new Map(); // projectPath -> projectId
const _noteRefMap = new Map();    // originalNoteId (filename) -> noteId
// --- END: Memory Optimization ---


const SCORE_ADJACENCY = 10;
const SCORE_START_WORD = 8;
const SCORE_MATCH = 5;
const PENALTY_GAP = -3;
const PENALTY_LEADING_GAP = -1; // Less penalty for first char
const MAX_RESULTS = 30;

/**
 * Custom fuzzy matching function.
 * @param {string} query The search query.
 * @param {string} text The text to search within.
 * @returns {object|null} An object with score and match indices, or null.
 */
function fuzzyMatch(query, text) {
    const queryLower = query.toLowerCase();
    const textLower = text.toLowerCase();
    let score = 0;
    let matches = [];
    let lastMatchIndex = -1;

    for (let i = 0; i < queryLower.length; i++) {
        const char = queryLower[i];
        const index = textLower.indexOf(char, lastMatchIndex + 1);

        if (index === -1) return null; // No match

        matches.push(index);
        score += SCORE_MATCH;

        if (lastMatchIndex !== -1) {
            const gap = index - lastMatchIndex - 1;
            if (gap === 0) {
                score += SCORE_ADJACENCY;
            } else {
                score += PENALTY_GAP * gap;
            }
        } else {
            // Penalize if the first match isn't at the start (could be adjusted or removed based on preference)
            score += PENALTY_LEADING_GAP * index;
        }

        // Bonus for matching start of a word
        if (index === 0 || [' ', '-', '_', '.', '/', '\\'].includes(text[index - 1])) {
            score += SCORE_START_WORD;
        }
        
        lastMatchIndex = index;
    }
    return { score, matches };
}

/** Clears the entire search index AND metadata maps. */
function clearIndex() {
    searchIndex = [];
    _projectMetadata.clear();
    _noteMetadata.clear();
    _projectRefMap.clear();
    _noteRefMap.clear();
    _nextProjectId = 1;
    _nextNoteId = 1;
}

/**
 * Adds an array of items to the search index.
 * The `items` array is expected to contain objects with full `metadata`
 * as generated by `projectManager`. This function will then optimize
 * how that data is stored internally.
 */
function addItemsToIndex(items) {
    if (!Array.isArray(items)) {
        return;
    }
    for (const item of items) {
        let projectId = null;
        if (item.metadata.projectPath) {
            if (!_projectRefMap.has(item.metadata.projectPath)) {
                projectId = _nextProjectId++;
                _projectRefMap.set(item.metadata.projectPath, projectId);
                _projectMetadata.set(projectId, {
                    name: item.metadata.projectName,
                    path: item.metadata.projectPath
                });
            } else {
                projectId = _projectRefMap.get(item.metadata.projectPath);
            }
        }

        let noteId = null;
        if (item.metadata.noteId) {
            if (!_noteRefMap.has(item.metadata.noteId)) {
                noteId = _nextNoteId++;
                _noteRefMap.set(item.metadata.noteId, noteId);
                _noteMetadata.set(noteId, {
                    name: item.metadata.noteName,
                    projectId: projectId
                });
            } else {
                noteId = _noteRefMap.get(item.metadata.noteId);
            }
        }

        // Create a lightweight item for the search index using numeric IDs
        const lightweightItem = {
            type: item.type,
            text: item.text,
            projectId: projectId,
            noteId: noteId,
            lineNumber: item.metadata.lineNumber || null
        };
        searchIndex.push(lightweightItem);
    }
}

/** Removes all index entries for a specific note. */
function removeIndexForNote(projectPath, originalNoteId) {
    const projectId = _projectRefMap.get(projectPath);
    const noteId = _noteRefMap.get(originalNoteId);

    if (noteId === undefined) return;

    searchIndex = searchIndex.filter(item => item.noteId !== noteId);
    
    _noteMetadata.delete(noteId);
    _noteRefMap.delete(originalNoteId);
}

/** Removes all index entries for a project. */
function removeIndexForProject(projectPath) {
    const projectId = _projectRefMap.get(projectPath);
    if (projectId === undefined) return;

    searchIndex = searchIndex.filter(item => item.projectId !== projectId);

    for (let [originalNoteId, noteId] of _noteRefMap.entries()) {
        const noteData = _noteMetadata.get(noteId);
        if (noteData && noteData.projectId === projectId) {
            _noteMetadata.delete(noteId);
            _noteRefMap.delete(originalNoteId);
        }
    }

    _projectMetadata.delete(projectId);
    _projectRefMap.delete(projectPath);
}


/** Performs a search against the in-memory index. */
function performSearch(query, context = {}) {
    if (!query || query.trim().length < 1) return [];

    let searchScope = searchIndex;

    // Filter the index based on the context (using numeric IDs)
    if (context.projectPath) {
        const projectId = _projectRefMap.get(context.projectPath);
        if (projectId !== undefined) {
            searchScope = searchScope.filter(item => item.projectId === projectId);
            searchScope = searchScope.filter(item => item.type !== 'project'); // Project names are not relevant when searching within a project
        }
    }
    if (context.noteId) {
        const noteId = _noteRefMap.get(context.noteId);
        if (noteId !== undefined) {
            searchScope = searchScope.filter(item => item.noteId === noteId);
            searchScope = searchScope.filter(item => item.type !== 'page'); // Page names are not relevant when searching within a specific note
        }
    }

    const results = [];
    let lowestScoreInResults = -Infinity;

    for (const item of searchScope) {
        const match = fuzzyMatch(query, item.text);

        if (match && (results.length < MAX_RESULTS || match.score > lowestScoreInResults)) {
            // Reconstruct full metadata for the result item by looking up references
            const projectMeta = item.projectId ? _projectMetadata.get(item.projectId) : null;
            const noteMeta = item.noteId ? _noteMetadata.get(item.noteId) : null;

            // Find original noteId (filename) for the result
            let originalNoteId = null;
            if (item.noteId) {
                for (let [key, value] of _noteRefMap.entries()) {
                    if (value === item.noteId) {
                        originalNoteId = key;
                        break;
                    }
                }
            }
            
            const fullMetadata = {
                projectPath: projectMeta ? projectMeta.path : null,
                projectName: projectMeta ? projectMeta.name : 'Unknown Project',
                noteId: originalNoteId,
                noteName: noteMeta ? noteMeta.name : 'Unknown Note',
                lineNumber: item.lineNumber
            };

            const scoredItem = {
                type: item.type,
                text: item.text,
                metadata: fullMetadata, // Attach the full, reconstructed metadata
                score: match.score,
                matches: match.matches
            };

            // Add to results, maintaining MAX_RESULTS and sorted by score
            if (results.length < MAX_RESULTS) {
                results.push(scoredItem);
                if (results.length === MAX_RESULTS) {
                    results.sort((a, b) => b.score - a.score);
                    lowestScoreInResults = results[MAX_RESULTS - 1].score;
                }
            } else {
                results[MAX_RESULTS - 1] = scoredItem; // Replace lowest score item
                results.sort((a, b) => b.score - a.score);
                lowestScoreInResults = results[MAX_RESULTS - 1].score;
            }
        }
    }

    // Final sort if results count is less than MAX_RESULTS
    if (results.length < MAX_RESULTS) {
        results.sort((a, b) => b.score - a.score);
    }
    
    return results;
}

export default {
    performSearch,
    clearIndex,
    addItemsToIndex,
    removeIndexForNote,
    removeIndexForProject,
    _getSearchIndex_FOR_TESTING: () => searchIndex,
    _getProjectMetadata_FOR_TESTING: () => _projectMetadata,
    _getNoteMetadata_FOR_TESTING: () => _noteMetadata,
};
